x-healthcheck: &healthcheck
  interval: 30s
  timeout: 5s
  retries: 15
  start_period: 3s
  start_interval: 1s

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres:

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=8GB"
      - "-c"
      - "wal_buffers=64MB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "effective_cache_size=24GB"
      - "-c"
      - "work_mem=64MB"
      - "-c"
      - "maintenance_work_mem=2GB"
      - "-c"
      - "random_page_cost=1.1"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

      # Required for healthcheck
      - PGPASSWORD=${POSTGRES_PASSWORD:?}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${PWD}/services/postgres/initdb.sql:/docker-entrypoint-initdb.d/zz-initdb.sql
    expose:
      - 5432
    networks:
      postgres:
        aliases:
          - pg.lokal

    healthcheck:
      <<: *healthcheck
      test: [CMD-SHELL, pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"]

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      postgres:
    expose:
      - 80
    ports:
      - ${PGADMIN_PORT:-8000}:80
    healthcheck:
      <<: *healthcheck
      test: [CMD-SHELL, wget -q --spider http://localhost]
